### PR TITLE
UNOISE

### PR DESCRIPTION
**Pull request by davidealbanese**
Dear All,
I just implemented the UNOISE algorithm (https://www.biorxiv.org/content/early/2016/10/15/081257.full.pdf+html) into VSEARCH. 

The command is quite similar to the one implemented in USEARCH (https://drive5.com/usearch/manual/cmd_unoise3.html) with the options `--minsize` and `--unoise_alpha`. All the options available for the clustering algorithms (with the exception of the global clustering threshold (`--id`) and the pairwise identity definition (`--iddef`)) remain valid.

This implementation does not include the chimera detection whereas the original does. Therefore, the additional chimera removal step is necessary. The abundance skew parameter is set to 16 in UCHIME3/UNOISE3 (USEARCH v10). So, the original command:
```bash
usearch -unoise3 uniques.fa -zotus zotus.fa
```
will be:
```bash
vsearch --unoise uniques.fa --sizein --sizeout --centroids zotus_chim.fa 
vsearch --sortbysize zotus_chim.fa --output zotus_sorted.fa
vsearch --uchime_denovo zotus_sorted.fa --abskew 16 --nonchimeras zotus.fa
```
I tested the implementation on the `Minimal-paired`, `MiSeq 2x250 16S V4` and `MiSeq 2x300 ITS` datasets (available at https://www.drive5.com/usearch/manual/pipe_examples.html) obtaining near identical results. Small differences are generated in the chimera filtering step, probably due to small deviations in the implementation.

I didn't update the man file but I'm happy to update it if you consider this pull request.
Comments are welcome,

Davide

### CODE REVIEW

**Comment by colinbrislawn** [comment]
Hello Davide,

I'm excited to see this functionality implemented in a open source program.

Can you share the tests you performed so we can replicate themselves? One main goal of vsearch is to 
```
- be as accurate or more accurate than usearch
- be as fast or faster than usearch
```
and the tests you provide will validate that.

Colin

**Comment by torognes** [comment]
Thanks, @davidealbanese, this seems promising! I'll look into the details soon.

**Comment by davidealbanese** [comment]
Hi Colin!
The attached file includes the preprocessed files:

* `uniques_minimal_paired.fa`: Minimal-paired (https://drive5.com/usearch/manual/ex_min2.html) 4259 seqs, 385 uniques, 337 singletons
* `uniques_miseq_16S.fa`: MiSeq 2x250 16S V4 (https://drive5.com/usearch/manual/ex_miseq.html) 212730 seqs, 3152 uniques, 0 singletons
* `uniques_miseq_ITS.fa`: MiSeq 2x300 ITS (https://drive5.com/usearch/manual/ex_miseq_its.html) 24964 seqs, 3647 uniques, 2815 singletons

a Python script (`compare_zotus.py`) which compares the ZOTUs found before and after the chimera filtering and a shell script (`run.sh`) that launches the analyses and the comparison. The python script requires Biopython to work. The USEARCH version used here is 10.0.240.

Decompress the file and run:
```sh
sh run.sh uniques_minimal_paired.fa
```
and the same for `uniques_miseq_16S.fa` and `uniques_miseq_ITS.fa`.

## Results

### uniques_minimal_paired.fa: 
```
***Before chimera filtering***
VSEARCH ZOTUs: 22
USEARCH ZOTUs: 22
ZOTUs in VSEARCH but not in USEARCH: 0
ZOTUs in USEARCH but not in VSEARCH: 0

***After chimera filtering***
VSEARCH ZOTUs: 22
USEARCH ZOTUs: 22
ZOTUs in VSEARCH but not in USEARCH: 0
ZOTUs in USEARCH but not in VSEARCH: 0
```

### uniques_miseq_16S.fa
```
***Before chimera filtering***
VSEARCH ZOTUs: 2527
USEARCH ZOTUs: 2527
ZOTUs in VSEARCH but not in USEARCH: 0
ZOTUs in USEARCH but not in VSEARCH: 0

***After chimera filtering***
VSEARCH ZOTUs: 2366
USEARCH ZOTUs: 2412
ZOTUs in VSEARCH but not in USEARCH: 16
ZOTUs in USEARCH but not in VSEARCH: 62
```

### uniques_miseq_ITS.fa
```
***Before chimera filtering***
VSEARCH ZOTUs: 121
USEARCH ZOTUs: 121
ZOTUs in VSEARCH but not in USEARCH: 0
ZOTUs in USEARCH but not in VSEARCH: 0

***After chimera filtering***
VSEARCH ZOTUs: 117
USEARCH ZOTUs: 118
ZOTUs in VSEARCH but not in USEARCH: 0
ZOTUs in USEARCH but not in VSEARCH: 1
```

As you can see, the implemented UNOISE algorithm in VSEARCH obtains identical results before the chimera filtering.

Let me know if this is enough,
Davide

[unoise.tar.gz](https://github.com/torognes/vsearch/files/1622103/unoise.tar.gz)

**Comment by torognes** [comment]
As I understand it, the proposed `unoise` command will not perform the full, same operation as the  usearch unoise command, since it does not perform the final chimera removal. Would it be possible to integrate the chimera removal as well into the same command? Otherwise, I think the command should be named differently in order to avoid confusion by users.

I have not had time to look more into the unoise algorithms yet. What are the differences between unoise (version 1) and unoise3? Does this command implement the initial unoise algorithm or the unoise3 algorithm?

**Comment by davidealbanese** [comment]
Hi @torognes,

> As I understand it, the proposed unoise command will not perform the full, same operation as the usearch unoise command, since it does not perform the final chimera removal.

Right. In my view, the chimeral removal should be a choice leave to the user. This feature could be classified as a "deliberate change".

>  Would it be possible to integrate the chimera removal as well into the same command?

I think so, but the `chimera()` function requires an input file. This implies the writing/reading of temporary files, right?

> I have not had time to look more into the unoise algorithms yet. What are the differences between unoise (version 1) and unoise3? Does this command implement the initial unoise algorithm or the unoise3 algorithm?

I don't know the unoise algorithm at version 1. I started from the [UNOISE2 paper](https://www.biorxiv.org/content/early/2016/10/15/081257.full.pdf+html), but the proposed implementation is determined to implement the `unoise3` command (without the chimera removal step, 	obviously).

In the UNOISE2 paper, I noticed an inconsistency, the distance between the sequences M and C seems to be computed only as the number of mismatches  and not as the "Levenshtein distance (number of differences including both substitutions and gaps)" (page 3). This is valid for both `unoise2` and `unoise3` commands.

In `unoise3` command, the default of the `-minsize` option has moved from 4 to 8 (https://drive5.com/usearch/manual/cmd_unoise3.html).

Moreover, at the page https://drive5.com/usearch/manual/unoise_algo.html:

> ... The implementation in unoise3 and uchime3_denovo is quite similar to UNOISE2 except for a change in parameters for chimera detection...

In `uchime3_denovo` the default value for `-abskew` is 16 (https://drive5.com/usearch/manual/cmd_uchime3_denovo.html).

In the comparisons above I used USEARCH version 10.0.240 which includes the `unoise3` command.

**Comment by davidealbanese** [comment]
UPDATE: the differences between the chimera detection in USEARCH and in VSEARCH are probably due to the new "denoised de novo (DDN) mode" introduced in the UCHIME2 [paper](https://www.biorxiv.org/content/biorxiv/early/2016/09/09/074252.full.pdf).

**Comment by torognes** [comment]
It might be possible to do both the denoising and chimera detection in one operation without writing any temporary files. I can look more into that later.

It seems like this denoising is actually a form of abundance-based clustering with an additional criterion for relative sequence abundances in a cluster (based on the number of differences between sequences) and also a minimum abundance value.

To reflect that this command does not perform the chimera detection part, could we name the command slightly differently? Perhaps `unoise_cluster` or `cluster_unoise`? Then we could perhaps later add a new command called just `unoise` or `unoise3` that performs both denoising and chimera detection? I think that could help users understand the difference.

**Comment by davidealbanese** [comment]
I agree with you. I think that `cluster_unoise` is a good option and it is consistent with the others `cluster_*` commands. 

Anyway, I am at you disposal if you need help for the complete `unoise/unoise3` command... I think that the first step could be the addition of the "denoised de novo mode" as an option in `uchime_denovo`.

**Comment by torognes** [comment]
Thanks for the contribution! Sorry for the delay, but now it is merged. I changed the command name and added some documentation.

**Comment by torognes** [comment]
I will release it as version 2.7.0 after some testing.

**Comment by colinbrislawn** [comment]
Hello Davide,

Can I get your advice on how to build a .biom table after you use `--cluster_unoise`? Edgar [suggests](https://www.drive5.com/usearch/manual/pipe_otutab.html) mapping all reads that are 97% similar for both OTUs and zOTUs, which I found surprising. Do you increase `--maxaccepts` due to the very similar centroids?

**Comment by davidealbanese** [comment]
Hi @colinbrislawn,

my opinion is that, in this particular case,  ``--maxaccepts 1`` is enough since ``usearch_global`` starts from the sequence with the highest number of 8-mers in common. However, using the top hit with a higher value of ``maxaccepts`` (>1) may increase sensitivity and higher values of ``id`` (e.g. 0.98) may increase specificity.

**Comment by colinbrislawn** [comment]
While this PR was merged long ago, I wanted to cross link to a discussion about default --id values. 
https://groups.google.com/forum/#!topic/vsearch-forum/ws7NEP68gO8 

What is the default `opt_id` when running `--cluster_unoise`?

**Comment by davidealbanese** [comment]
The UNOISE algo ignores the `id` param (see https://doi.org/10.1101/081257).

**Comment by colinbrislawn** [comment]
It appears that usearch _does_ make use of this setting, but "is not documented or supported for the unoise3 command". 
🙀 
I'm not sure what we should do about this...

**Comment by davidealbanese** [comment]
Could you explain better?

**Comment by colinbrislawn** [comment]
Sure. Take a look at this [vsearch form post](https://groups.google.com/forum/#!topic/vsearch-forum/ws7NEP68gO8) in which Mafalda has posted results from `usearch -unoise3` and `vsearch --cluster_unoise` with different values of `-id`. These parameter sweeps shows the effect of id, which are not (currently) documented and may not be intended. 

Let me know if those results in the post make sense.

**Comment by davidealbanese** [comment]
The problem was the link between `opt_weak_id` and `opt_id` when `opt_weak_id` is not specified. Fixed in #362. Let me know,

Davide

**Comment by MafGal** [comment]
Here a summary of tests and differences.

22 02 2019_comparison_usearch-unose3_vs_vsearch-unoise3

**Comment by torognes** [comment]
@davidealbanese's changes has been merged into vsearch version 2.11.1. Thanks for illuminating this issue.

**Pull request merged**
