### PR TITLE
Windows Modifications For Compilation with Visual Studio 2015

### PR DESCRIPTION
**Pull request by mothur-westcott**
The VS_vsearch folder is a visual studio project created from 1.9.10 with the source from the rest of the pull request.  It compiles, but I was getting some runtime errors and would love some help debugging or improvements.

### CODE REVIEW

**Comment by torognes** [comment]
Thanks a lot for your PR. I am about to set up WIndows 7 in a VM on my Mac to perform development and adaptation for Windows there. I am unsure whether we should use a visual studio project or if it is possible just to use an ordinary makefile to build on Windows using command-line tools. The latter option would probably involve the fewest changes. Anyway I am sure the modifications you have made here will be very useful in the process, although I will probably review all of them carefully and add them manually.

**Comment by mothur-westcott** [comment]
👍

**Comment by torognes** [comment]
Modifications for 64-bit Windows are now included in the `win` branch and a pre-release binary is available with a Windows executable.

**Comment by torognes** [comment]
Windows support has been included in version 2.4.0 just released.

**Pull request closed without merging**
